### ISSUE TITLE
conda didn't install

### ISSUE THREAD

**Issue by JVTEAM** [KeithIMyers/Crostini-Machine-Learning#1]
I went to run your conda activate tensorflow_env and conda was not installed after running the script.

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Traceback (most recent call last):
  File "/home/jvteam/miniconda/bin/conda", line 7, in <module>
    from conda.cli import main
ImportError: No module named conda.cli
Traceback (most recent call last):
  File "/home/jvteam/miniconda/bin/conda", line 7, in <module>
    from conda.cli import main
ImportError: No module named conda.cli
Traceback (most recent call last):
  File "/home/jvteam/miniconda/bin/conda", line 7, in <module>
    from conda.cli import main
ImportError: No module named conda.cli
Traceback (most recent call last):
  File "/home/jvteam/miniconda/bin/conda", line 7, in <module>
    from conda.cli import main
ImportError: No module named conda.cli

**Comment by KeithIMyers** [comment]
Hello,
Can you let me know what device you are using to install this on?

**Comment by JVTEAM** [comment]
Pixelbook

**Comment by KeithIMyers** [comment]
Thanks. I will give it a test to see if something changed

**Comment by KeithIMyers** [comment]
Just a update - I blew away my Crostini instance and started with a fresh install on my Pixelbook, I was able to confirm that it is indeed broken.  Sorry for the late response, just wanted to back everything up before I did this. 

My initial guesses are either the changes to deprecate Python2 or the move from Debian Stretch to Buster.

**Comment by JVTEAM** [comment]
I was able to get conda to install outside of the script, but it obviously lacks your virtual environment.

**Comment by KeithIMyers** [comment]
Resolved with latest update
