### ISSUE TITLE
Coral USB didn't seem to have any effect

### ISSUE THREAD

**Issue by JVTEAM** [KeithIMyers/Crostini-Machine-Learning#2]
Using the Coral USB accellerator, there seemed to be no effect from the install script.  I still had to perform all the steps on the get started page to make it work.  It did however, in the end work.

https://coral.ai/docs/accelerator/get-started/

**Comment by KeithIMyers** [comment]
Updated code to reflect the new apt repos as well as added the option to chose to use the Standard TPU or the Max Frequency TPU
